//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba_7.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laba_7.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        internal static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите подключиться к сети {0}?.
        /// </summary>
        internal static string ConnectConfirmText {
            get {
                return ResourceManager.GetString("ConnectConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wifi Networks.
        /// </summary>
        internal static string H1Title {
            get {
                return ResourceManager.GetString("H1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///	&lt;name&gt;{0}&lt;/name&gt;
        ///	&lt;SSIDConfig&gt;
        ///		&lt;SSID&gt;
        ///			&lt;name&gt;{0}&lt;/name&gt;
        ///		&lt;/SSID&gt;
        ///	&lt;/SSIDConfig&gt;
        ///	&lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///	&lt;connectionMode&gt;manual&lt;/connectionMode&gt;
        ///	&lt;MSM&gt;
        ///		&lt;security&gt;
        ///			&lt;authEncryption&gt;
        ///				&lt;authentication&gt;open&lt;/authentication&gt;
        ///				&lt;encryption&gt;none&lt;/encryption&gt;
        ///				&lt;useOneX&gt;false&lt;/useOneX&gt;
        ///			&lt;/authEncryption&gt;
        ///		&lt;/security&gt;
        ///	&lt;/MSM&gt;
        ///&lt;/WLANProfile&gt;.
        /// </summary>
        internal static string OPEN_NETWORK {
            get {
                return ResourceManager.GetString("OPEN_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input password here.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WiFi IPD Labs.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;US-ASCII&quot;?&gt;
        ///&lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///    &lt;name&gt;{0}&lt;/name&gt;
        ///    &lt;SSIDConfig&gt;
        ///        &lt;SSID&gt;
        ///            &lt;name&gt;{0}&lt;/name&gt;
        ///        &lt;/SSID&gt;
        ///    &lt;/SSIDConfig&gt;
        ///    &lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///    &lt;connectionMode&gt;auto&lt;/connectionMode&gt;
        ///    &lt;autoSwitch&gt;false&lt;/autoSwitch&gt;
        ///    &lt;MSM&gt;
        ///        &lt;security&gt;
        ///            &lt;authEncryption&gt;
        ///                &lt;authentication&gt;{1}&lt;/authentication&gt;
        ///                &lt;encryption&gt;{2}&lt;/enc [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string WPAPSK {
            get {
                return ResourceManager.GetString("WPAPSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;US-ASCII&quot;?&gt;
        ///&lt;WLANProfile xmlns=&quot;http://www.microsoft.com/networking/WLAN/profile/v1&quot;&gt;
        ///    &lt;name&gt;SampleWPA2PSK&lt;/name&gt;
        ///    &lt;SSIDConfig&gt;
        ///        &lt;SSID&gt;
        ///            &lt;name&gt;SampleWPA2PSK&lt;/name&gt;
        ///        &lt;/SSID&gt;
        ///    &lt;/SSIDConfig&gt;
        ///    &lt;connectionType&gt;ESS&lt;/connectionType&gt;
        ///    &lt;connectionMode&gt;auto&lt;/connectionMode&gt;
        ///    &lt;autoSwitch&gt;false&lt;/autoSwitch&gt;
        ///    &lt;MSM&gt;
        ///        &lt;security&gt;
        ///            &lt;authEncryption&gt;
        ///                &lt;authentication&gt;WPA2PSK&lt;/authentication&gt;
        ///             [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string WPAPSK2 {
            get {
                return ResourceManager.GetString("WPAPSK2", resourceCulture);
            }
        }
    }
}
